// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _kernel3_HH_
#define _kernel3_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "kernel3_fadd_32nsbkb.h"

namespace ap_rtl {

struct kernel3 : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<10> > hist_address0;
    sc_out< sc_logic > hist_ce0;
    sc_out< sc_logic > hist_we0;
    sc_out< sc_lv<32> > hist_d0;
    sc_in< sc_lv<32> > hist_q0;
    sc_out< sc_lv<10> > weight_address0;
    sc_out< sc_logic > weight_ce0;
    sc_in< sc_lv<32> > weight_q0;
    sc_out< sc_lv<10> > index_address0;
    sc_out< sc_logic > index_ce0;
    sc_in< sc_lv<32> > index_q0;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    kernel3(sc_module_name name);
    SC_HAS_PROCESS(kernel3);

    ~kernel3();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    kernel3_fadd_32nsbkb<1,4,32,32,32>* kernel3_fadd_32nsbkb_U1;
    sc_signal< sc_lv<23> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<11> > i_reg_194;
    sc_signal< sc_lv<32> > hist0_1_reg_205;
    sc_signal< sc_lv<32> > index5_reg_216;
    sc_signal< sc_lv<32> > index1_1_reg_226;
    sc_signal< sc_lv<32> > index0_3_reg_236;
    sc_signal< sc_lv<32> > hist1_1_reg_246;
    sc_signal< sc_lv<32> > hist5_reg_258;
    sc_signal< sc_lv<32> > reg_275;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state10;
    sc_signal< sc_lv<32> > reg_280;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<1> > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter0;
    sc_signal< sc_lv<1> > exitcond_reg_663;
    sc_signal< sc_lv<32> > reg_285;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<32> > ap_pipeline_reg_pp0_iter1_reg_285;
    sc_signal< sc_lv<32> > hist_load_reg_585;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > grp_fu_271_p2;
    sc_signal< sc_lv<32> > hist0_reg_605;
    sc_signal< sc_lv<32> > hist4_v_fu_306_p3;
    sc_signal< sc_lv<32> > hist4_v_reg_611;
    sc_signal< sc_lv<32> > index4_fu_314_p3;
    sc_signal< sc_lv<32> > index4_reg_616;
    sc_signal< sc_lv<1> > ap_CS_fsm_state9;
    sc_signal< sc_lv<32> > hist1_reg_638;
    sc_signal< sc_lv<32> > index1_1_ph_fu_338_p3;
    sc_signal< sc_lv<32> > index1_1_ph_reg_643;
    sc_signal< sc_lv<32> > index0_3_ph_fu_365_p3;
    sc_signal< sc_lv<32> > index0_3_ph_reg_648;
    sc_signal< sc_lv<32> > hist1_2_ph_v_fu_379_p3;
    sc_signal< sc_lv<32> > hist1_2_ph_v_reg_653;
    sc_signal< sc_lv<32> > hist2_reg_658;
    sc_signal< sc_lv<1> > ap_CS_fsm_state15;
    sc_signal< sc_lv<1> > exitcond_fu_387_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage0;
    sc_signal< sc_lv<1> > ap_pipeline_reg_pp0_iter1_exitcond_reg_663;
    sc_signal< sc_lv<11> > i_1_fu_399_p2;
    sc_signal< sc_lv<11> > i_1_reg_677;
    sc_signal< sc_lv<1> > sel_tmp7_fu_452_p2;
    sc_signal< sc_lv<1> > sel_tmp7_reg_687;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage2;
    sc_signal< sc_lv<32> > index1_2_fu_472_p3;
    sc_signal< sc_lv<32> > index1_2_reg_693;
    sc_signal< sc_lv<32> > index0_1_fu_488_p3;
    sc_signal< sc_lv<32> > index0_1_reg_698;
    sc_signal< sc_lv<32> > sel_tmp9_fu_504_p3;
    sc_signal< sc_lv<32> > sel_tmp9_reg_703;
    sc_signal< sc_lv<32> > hist2_2_pn_fu_519_p3;
    sc_signal< sc_lv<1> > ap_CS_fsm_pp0_stage3;
    sc_signal< sc_logic > ap_enable_reg_pp0_iter1;
    sc_signal< sc_lv<1> > tmp_10_fu_548_p2;
    sc_signal< sc_lv<1> > tmp_10_reg_724;
    sc_signal< sc_lv<1> > ap_CS_fsm_state24;
    sc_signal< sc_lv<1> > tmp_14_fu_559_p2;
    sc_signal< sc_lv<1> > tmp_14_reg_728;
    sc_signal< sc_lv<1> > ap_CS_fsm_state25;
    sc_signal< sc_lv<1> > ap_CS_fsm_state16;
    sc_signal< sc_lv<11> > i_phi_fu_198_p4;
    sc_signal< sc_lv<32> > hist0_1_phi_fu_209_p4;
    sc_signal< sc_lv<32> > index5_phi_fu_219_p4;
    sc_signal< sc_lv<32> > index1_1_phi_fu_229_p4;
    sc_signal< sc_lv<32> > index0_3_phi_fu_239_p4;
    sc_signal< sc_lv<32> > hist1_1_phi_fu_251_p4;
    sc_signal< sc_lv<32> > hist5_phi_fu_262_p4;
    sc_signal< sc_lv<64> > tmp_fu_290_p1;
    sc_signal< sc_lv<64> > tmp_4_fu_295_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_322_p1;
    sc_signal< sc_lv<64> > tmp_3_fu_393_p1;
    sc_signal< sc_lv<64> > tmp_13_fu_405_p1;
    sc_signal< sc_lv<64> > tmp_17_fu_532_p1;
    sc_signal< sc_lv<1> > tmp_15_fu_526_p2;
    sc_signal< sc_lv<64> > tmp_7_fu_543_p1;
    sc_signal< sc_lv<1> > tmp_1_fu_537_p2;
    sc_signal< sc_lv<64> > tmp_12_fu_554_p1;
    sc_signal< sc_lv<64> > tmp_16_fu_565_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state26;
    sc_signal< sc_lv<32> > grp_fu_271_p0;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > tmp_2_fu_300_p2;
    sc_signal< sc_lv<1> > tmp_6_fu_327_p2;
    sc_signal< sc_lv<1> > tmp_8_fu_333_p2;
    sc_signal< sc_lv<1> > sel_tmp_fu_346_p2;
    sc_signal< sc_lv<1> > sel_tmp3_fu_352_p2;
    sc_signal< sc_lv<32> > sel_tmp4_fu_358_p3;
    sc_signal< sc_lv<32> > sel_tmp53_v_fu_372_p3;
    sc_signal< sc_lv<1> > tmp_5_fu_410_p2;
    sc_signal< sc_lv<1> > tmp_9_fu_416_p2;
    sc_signal< sc_lv<1> > sel_tmp1_fu_428_p2;
    sc_signal< sc_lv<1> > sel_tmp6_demorgan_fu_440_p2;
    sc_signal< sc_lv<1> > tmp_11_fu_422_p2;
    sc_signal< sc_lv<1> > sel_tmp6_fu_446_p2;
    sc_signal< sc_lv<1> > sel_tmp2_fu_434_p2;
    sc_signal< sc_lv<1> > or_cond_fu_458_p2;
    sc_signal< sc_lv<32> > newSel_fu_464_p3;
    sc_signal< sc_lv<32> > sel_tmp5_fu_480_p3;
    sc_signal< sc_lv<32> > sel_tmp8_fu_496_p3;
    sc_signal< sc_lv<32> > index0_6_fu_512_p3;
    sc_signal< sc_lv<23> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<23> ap_ST_fsm_state1;
    static const sc_lv<23> ap_ST_fsm_state2;
    static const sc_lv<23> ap_ST_fsm_state3;
    static const sc_lv<23> ap_ST_fsm_state4;
    static const sc_lv<23> ap_ST_fsm_state5;
    static const sc_lv<23> ap_ST_fsm_state6;
    static const sc_lv<23> ap_ST_fsm_state7;
    static const sc_lv<23> ap_ST_fsm_state8;
    static const sc_lv<23> ap_ST_fsm_state9;
    static const sc_lv<23> ap_ST_fsm_state10;
    static const sc_lv<23> ap_ST_fsm_state11;
    static const sc_lv<23> ap_ST_fsm_state12;
    static const sc_lv<23> ap_ST_fsm_state13;
    static const sc_lv<23> ap_ST_fsm_state14;
    static const sc_lv<23> ap_ST_fsm_state15;
    static const sc_lv<23> ap_ST_fsm_state16;
    static const sc_lv<23> ap_ST_fsm_pp0_stage0;
    static const sc_lv<23> ap_ST_fsm_pp0_stage1;
    static const sc_lv<23> ap_ST_fsm_pp0_stage2;
    static const sc_lv<23> ap_ST_fsm_pp0_stage3;
    static const sc_lv<23> ap_ST_fsm_state24;
    static const sc_lv<23> ap_ST_fsm_state25;
    static const sc_lv<23> ap_ST_fsm_state26;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_13;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<11> ap_const_lv11_3;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_FFFFFFFF;
    static const sc_lv<11> ap_const_lv11_400;
    static const sc_lv<11> ap_const_lv11_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_pp0_stage0();
    void thread_ap_CS_fsm_pp0_stage1();
    void thread_ap_CS_fsm_pp0_stage2();
    void thread_ap_CS_fsm_pp0_stage3();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state25();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_exitcond_fu_387_p2();
    void thread_grp_fu_271_p0();
    void thread_hist0_1_phi_fu_209_p4();
    void thread_hist1_1_phi_fu_251_p4();
    void thread_hist1_2_ph_v_fu_379_p3();
    void thread_hist2_2_pn_fu_519_p3();
    void thread_hist4_v_fu_306_p3();
    void thread_hist5_phi_fu_262_p4();
    void thread_hist_address0();
    void thread_hist_ce0();
    void thread_hist_d0();
    void thread_hist_we0();
    void thread_i_1_fu_399_p2();
    void thread_i_phi_fu_198_p4();
    void thread_index0_1_fu_488_p3();
    void thread_index0_3_ph_fu_365_p3();
    void thread_index0_3_phi_fu_239_p4();
    void thread_index0_6_fu_512_p3();
    void thread_index1_1_ph_fu_338_p3();
    void thread_index1_1_phi_fu_229_p4();
    void thread_index1_2_fu_472_p3();
    void thread_index4_fu_314_p3();
    void thread_index5_phi_fu_219_p4();
    void thread_index_address0();
    void thread_index_ce0();
    void thread_newSel_fu_464_p3();
    void thread_or_cond_fu_458_p2();
    void thread_sel_tmp1_fu_428_p2();
    void thread_sel_tmp2_fu_434_p2();
    void thread_sel_tmp3_fu_352_p2();
    void thread_sel_tmp4_fu_358_p3();
    void thread_sel_tmp53_v_fu_372_p3();
    void thread_sel_tmp5_fu_480_p3();
    void thread_sel_tmp6_demorgan_fu_440_p2();
    void thread_sel_tmp6_fu_446_p2();
    void thread_sel_tmp7_fu_452_p2();
    void thread_sel_tmp8_fu_496_p3();
    void thread_sel_tmp9_fu_504_p3();
    void thread_sel_tmp_fu_346_p2();
    void thread_tmp_10_fu_548_p2();
    void thread_tmp_11_fu_422_p2();
    void thread_tmp_12_fu_554_p1();
    void thread_tmp_13_fu_405_p1();
    void thread_tmp_14_fu_559_p2();
    void thread_tmp_15_fu_526_p2();
    void thread_tmp_16_fu_565_p1();
    void thread_tmp_17_fu_532_p1();
    void thread_tmp_1_fu_537_p2();
    void thread_tmp_2_fu_300_p2();
    void thread_tmp_3_fu_393_p1();
    void thread_tmp_4_fu_295_p1();
    void thread_tmp_5_fu_410_p2();
    void thread_tmp_6_fu_327_p2();
    void thread_tmp_7_fu_543_p1();
    void thread_tmp_8_fu_333_p2();
    void thread_tmp_9_fu_416_p2();
    void thread_tmp_fu_290_p1();
    void thread_tmp_s_fu_322_p1();
    void thread_weight_address0();
    void thread_weight_ce0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
